export const SET_INGREDIENTS_BUN = "SET_INGREDIENTS_BUN";
export const DEL_INGREDIENTS_MAIN = "DEL_INGREDIENTS_MAIN";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const ADD_INGREDIENTS_MAIN = "ADD_INGREDIENTS_MAIN";
export const SET_INGREDIENTS_ID = "SET_INGREDIENTS_ID";
export const UPDATE_SELECTED_INGREDIENTS = "UPDATE_SELECTED_INGREDIENTS";
